version: '3'
services:
  mysql:
    image: mysql_db
    build: /home/ubuntu/new_chatapp1/Database
    container_name: mydb
    volumes:
    - mysqldata:/var/lib/mysql
  backend:
    image: backend_image
    build: /home/ubuntu/new_chatapp1
    container_name: backend
    links:
    - mysql
    volumes:
    - /home/ubuntu/new_chatapp1:/new_chatapp1

  frontend:
    image: frontend_image
    build: /home/ubuntu/new_chatapp1/Frontend 
    container_name: frontend
    links:
    - backend
    ports:
    - 80:80
volumes:
  mysqldata:
